name: dropseq_hdf5
channels:
  - conda-forge
  - defaults
dependencies:
  - bzip2=1.0.8
  - ca-certificates
  - libffi=3.4.2
  - libsqlite=3.46.0
  - libzlib=1.3.1
  - ncurses=6.5
  - openssl=3.3.1
  - pip=24.2
  - python=3.8
  - readline=8.2
  - setuptools
  - tk=8.6.13
  - wheel=0.44.0
  - xz
  - pip:
    - anndata==0.7.6
    - h5py==3.11.0
    - natsort==8.4.0
    - numexpr==2.8.6
    - numpy==1.21.2
    - packaging==24.1
    - pandas==2.0.3
    - python-dateutil==2.9.0.post0
    - pytz==2024.1
    - scipy==1.7.1
    - six==1.16.0
    - tables==3.6.1
    - tzdata==2024.1
    - xlrd==1.2.0
