# based on:
# https://github.com/broadinstitute/Drop-seq/new/master?filename=.github%2Fworkflows%2Fdocker-publish.yml&workflow_template=ci%2Fdocker-publish
name: DropSeq Reusable Docker

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

on:
  workflow_call:
      inputs:
        registry:
          description: 'Name of the docker registry'
          required: true
          type: string
        image_name:
          description: 'Name of the docker image'
          required: true
          type: string
        dockerfile:
          description: 'Path to the Dockerfile'
          required: true
          type: string

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Set up BuildKit Docker container builder to be able to build
      # multi-platform images and export cache
      # https://github.com/docker/setup-buildx-action
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Get source version from the git log.
      # Do not push pull requests or pushes to master branch.
      - name: Build variables
        id: build-variables
        run: |
          echo "srcversion=$(git log -1 --date=short --pretty=format:"%ad_%h")" >> $GITHUB_OUTPUT
          echo "docker_current=${{
            github.event_name == 'workflow_dispatch' && github.ref == 'refs/heads/master'
          }}" >> $GITHUB_OUTPUT
          echo "docker_push=${{ !(
            github.event_name == 'pull_request' ||
            (github.event_name == 'push' && github.ref == 'refs/heads/master')
          ) }}" >> $GITHUB_OUTPUT

      # Login against a Docker registry except on PR
      # https://github.com/docker/login-action
      - name: Log into registry ${{ inputs.registry }}
        if: steps.build-variables.outputs.docker_push == 'true'
        uses: docker/login-action@v3.0.0
        with:
          registry: ${{ inputs.registry }}
          username: ${{ secrets.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_PASSWORD }}

      # Extract metadata (tags, labels) for Docker
      # https://github.com/docker/metadata-action
      - name: Extract Docker metadata
        id: docker-metadata
        uses: docker/metadata-action@v5
        with:
          images: ${{ inputs.registry }}/${{ inputs.image_name }}
          tags: |
            type=semver,pattern={{version}}
            type=raw,value=${{ steps.build-variables.outputs.srcversion }}
            type=raw,value=current,enable=${{ steps.build-variables.outputs.docker_current }}

      # Build and push Docker image with Buildx (don't push on PR)
      # https://github.com/docker/build-push-action
      - name: Build and push Docker image
        id: build-and-push
        uses: docker/build-push-action@v5
        with:
          file: ${{ inputs.dockerfile }}
          context: .
          push: ${{ steps.build-variables.outputs.docker_push }}
          tags: ${{ steps.docker-metadata.outputs.tags }}
          labels: ${{ steps.docker-metadata.outputs.labels }}
          build-args: |
            SRCVERSION=${{ steps.build-variables.outputs.srcversion }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          # Stop buildx from pushing provenance files for our images.
          # https://docs.docker.com/build/ci/github-actions/attestations/#default-provenance
          # https://github.com/docker/setup-buildx-action/issues/187#issuecomment-1398199592
          provenance: false
