# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
#
# See https://github.com/r-lib/actions/tree/master/examples#readme for
# additional example workflows available for the R community.

name: DropSeq.dropulation R package

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
    paths: 'src/R/packages/DropSeq.dropulation/**'

permissions:
  contents: read

# See https://dirk.eddelbuettel.com/blog/code/r4/ for using r2u to speed up dependency loading
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: rocker/r2u:latest
    steps:
      - uses: actions/checkout@v3
      - name: SessionInfo
        run: R -q -e 'sessionInfo()'
      - name: Install dependencies
        run: |
          setwd("src/R/packages/DropSeq.dropulation")
          install.packages(c("rcmdcheck"))
          remotes::install_deps(dependencies = TRUE)
        shell: Rscript {0}
        env:
          GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }} # this is needed because some deps are downloaded from github
      - name: Check
        run: |
          setwd("src/R/packages/DropSeq.dropulation")
          rcmdcheck::rcmdcheck(args = "--no-manual", error_on = "error")
        shell: Rscript {0}
