name: Python unit tests for dropseq_util

permissions:
  contents: read

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
    paths:
      - '.github/workflows/python-dropseq-util.yml'
      - '.github/workflows/python-package.yml'
      - 'src/python/dropseq_util/**'

jobs:
  call-python-reusable:
    uses: ./.github/workflows/python-package.yml
    with:
      package_name: util
    secrets: inherit
