name: unit tests for dropseq python package

permissions:
  contents: read

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
    paths:
      - '.github/workflows/python.yml'
      - 'src/python/**'

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: ${{ inputs.python_version }}
    - name: Install package including dependencies
      run: |
        cd src/python
        pip install .
    - name: Test with unittest
      run: |
        cd src/python
        PYTHONPATH=src python -m unittest discover -s tests
